name = input("What is your name? ")
print(name)
age = int(input("How old are you? "))
print(age)
grade = int(input("Which grade are you study? "))
print(grade)
live = input("Which state are live? ")
print(live)
father = input("What is your father name? ")
print(father)
mother = input("What is your mother name? ")
print(mother)
contect = input("What is contect number? ")
print(contect)
color = input("What is your favourite color? ")
print(color)